# Generated by Django 5.0.6 on 2024-05-16 06:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('health_issues', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('adoption_status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted')], max_length=20)),
                ('rescue_organization', models.CharField(max_length=80)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='pet_images/')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('availability', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('weekends', 'Weekends Only'), ('evenings', 'Evenings Only')], max_length=20)),
                ('relevant_experience', models.TextField()),
                ('reason_for_volunteering', models.TextField()),
                ('skills', models.TextField()),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionFosterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('retired', 'Retired'), ('unemployed', 'Unemployed'), ('student', 'Student')], max_length=20)),
                ('other_household_pets', models.TextField()),
                ('is_married', models.BooleanField(default=False)),
                ('children', models.BooleanField(default=False)),
                ('children_description', models.TextField()),
                ('application_status', models.CharField(max_length=20)),
                ('pet_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
    ]
